### PR TITLE
more info lmao

### PR DESCRIPTION
**Pull request by Ali00035v2**
btw my discord got locked and i cant make a new one, see me on matrix.org

### CODE REVIEW

**Comment by danik4985** [comment]
ali do you have telegram?

**Comment by Ali00035v2** [comment]
> ali do you have telegram?

no

**Comment by danik4985** [comment]
get telegram then

**Comment by danik4985** [comment]
pleas

**Comment by danik4985** [comment]
matrix broke i cant send messages

**Comment by Ali00035v2** [comment]
> get telegram then

my phone is broken

**Comment by danik4985** [comment]
telgram desktop

**Comment by Ali00035v2** [comment]
merge this pr first

**Comment by Ali00035v2** [comment]
> matrix broke i cant send messages

which client

**Comment by danik4985** [comment]
element

**Comment by Ali00035v2** [comment]
use the web version

**Comment by danik4985** [comment]
i am using that

**Pull request merged**
